spring.application.name=backend

server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://db.dmibrkhpyxvdymonllhv.supabase.co:5432/postgres
spring.datasource.username=postgres.dmibrkhpyxvdymonllhv
spring.datasource.password=${DB_PASSWORD}

spring.datasource.hikari.data-source-properties.sslmode=require

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

riot.api.key=${RIOT_API_KEY}