spring.application.name=backend

server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:5432/postgres}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres.dmibrkhpyxvdymonllhv}
spring.datasource.password=${LOL_TRACKER_DB_PASSWORD}
spring.datasource.hikari.data-source-properties.sslmode=require

spring.datasource.hikari.data-source-properties.prepareThreshold=0
spring.datasource.hikari.data-source-properties.cachePrepStmts=false
spring.datasource.hikari.data-source-properties.useServerPrepStmts=false

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

riot.api.key=${LOL_TRACKER_RIOT_API_KEY}